name: Deploy To Google Cloud

# TODO: might make this run only on tags
on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

jobs:
  deploy_functions:
    name: deploy functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          version: '289.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud config set core/project "$PROJECT_ID"
      - run: .github/workflows/deploy-functions.sh
