name: Build Standalone Executable

on:
  push:
    tags:
      - standalone-v*
    branches:
      - master
    paths:
      - standalone/*


jobs:
  build_mac:
    name: build on macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: standalone
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build executable
        working-directory: standalone
        run: pyinstaller --windowed main.spec
      - run: zip -r VideoAligner-macOS.zip VideoAligner.app/
        working-directory: standalone/dist
      - uses: actions/upload-artifact@v2
        with:
          name: VideoAligner-macOS.zip
          path: standalone/dist/VideoAligner-macOS.zip
  build_window:
    name: build on windows
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: git config --global core.symlinks true
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: standalone
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build executable
        working-directory: standalone
        run: pyinstaller --windowed main.spec
      - uses: actions/upload-artifact@v2
        with:
          name: VideoAligner-windows.exe
          path: standalone/dist/aligner.exe
